### ISSUE TITLE
Ressources ---> Resources

### ISSUE THREAD

**Issue by mnaklicki** [raykyn/MittSim#11]
The word "resources" is misspelled in the interface. Instead of "ressources" is should be "resources".

FIX:
Change all instances of the word "ressource" or "ressources" in the code to "resource" or "resources".

**Comment by raykyn** [comment]
Thank you, I will correct it with the next commit.

**Comment by raykyn** [comment]
Done in the new_version branch. Fixed as soon as we finally merge.

**Comment by mnaklicki** [comment]
Hey, could you reply to me on Reddit? Thanks.
